<?php

use Magento\Framework\Escaper;
use Magento\Catalog\Block\Product\View\Details;

/** @var Details $block */
/** @var Escaper $escaper */

$helper = $this->helper("DeveloperHub\ProductCustomTabs\Helper\Config");
$layout = $block->getLayout();
?>
<?php $helper->ShowCustomTabs() ? $block->productContainCustomTab($layout, $block->getRequest()->getParams('id')) : null ?>
<div class="product info detailed">
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')):?>
         <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!$html || !trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $escaper->escapeUrl($alias) ?>"
                       id="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>-title"
                     id="<?= $escaper->escapeHtmlAttr($alias) ?>" data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
<?php endif; ?>
</div>
